### ISSUE TITLE
Addressing issues for chapter on predicting GNSS data with HelioML computing capabilities

### ISSUE THREAD

**Issue by rmcgranaghan** [HelioML/HelioML#12]
#### Description: 
I emailed a notebook that will form the foundation for a new chapter in the textbook. This notebook uses data from the CHAIN ground-based network of Global Navigation Satellite Systems (GNSS) receivers to study the ionosphere and space weather. There are data volume and computation issues that need to be checked to ensure they are appropriate for the computational capabilities of HelioML. 

#### Open questions: 
1. Please take a look at the notebook I e-mailed you and let me know if it works with your cluster constraints

**Comment by jmason86** [comment]
That's top of my list for things to do next week!

**Comment by jmason86** [comment]
Alright I'm part way through the notebook running it locally with our helioml environment and so far, mostly good. Here's some action items for you @rmcgranaghan 

- [ ] Update your download URL to: `'https://ndownloader.figshare.com/files/12388631'` for 2015 and `'https://ndownloader.figshare.com/files/12388670'` for 2016. Those strings can be passed directly to `pandas.read_csv()` and it works perfectly. It took me 6 minutes to download 2015 so if the monitoring bar turns out to be difficult to implement, you could just include a comment saying that it's expected to take about that long. 
- [ ] Include `%matplotlib inline`
- [ ] There's a deprecation warning when you call `mlab.normpdf()`: MatplotlibDeprecationWarning: scipy.stats.norm.pdf that prevents the plots from showing up. Surely this functionality still exists, so could you just update the syntax? 
- [ ] In your own execution of the code (I haven't gotten to executing this cells yet), you get the error: ValueError: unrecognized kwargs: ['xmin'] -- I don't actually find any use of 'xmin' in that cell, so is this output just a result from a previous execution? 
- [ ] The narrative text in here is already really good but adding a little bit for interpretation of results would make it perfect, e.g., a sentence or two discussing the confusion matrix result (is it good, bad, indicative of something?) 
- [ ] You can [issue a PR with your notebook under a new folder: content/05/1/](https://github.com/HelioML/HelioML/blob/master/CONTRIBUTING.md). We can then keep hashing through this stuff there, tracking updated commits, and ultimately you'll get the credit on GitHub for your contribution. Let me know if you need any guidance with the process.

**Comment by jmason86** [comment]
Update: I've now run all of the code locally in the textbook environment and it works! My execution times were similar (3 hours for one cell, 1 hour for others, ten minutes or so for some). Next step will be figuring out if our existing cluster has the resources to run this and what kind of execution times we're looking at.

**Comment by rmcgranaghan** [comment]
Hi James

Thanks for the helpful input. I forked the HelioML repo and made the
appropriate adjustments there. I believe I have addressed each of your
comments. A few quick notes:

   - Yes, the 'xmin' error should be a carry-over from a previous run.
   Sorry about that.
   - Now that my own forked version is updated, is the next step to push to
   the master HelioML repo? Thank you for helping me navigate github while I'm
   still building up my ability to contribute to open source projects!

Thanks!
Ryan

*Ryan McGranaghan* - Aerospace Engineering Scientist | Principal Data
Scientist


          ASTRA, LLC

          282 Century Place, Suite 1000  |  Louisville, CO  80027
          Contact
          WeWork c/o Ryan McGranaghan, 641 S Street NW, Washington, DC 20001
          865.804.2169  |  ryan.mcgranaghan@gmail.com /
rmcgranaghan@astraspace.net |  astraspace.net

**Comment by jmason86** [comment]
@rmcgranaghan Great! Yes, you're basically right. You won't be able to push to the main repo master branch directly. Instead you'll basically be requesting to do so and then Monica+I will review/approve it and that will do the actual merge. The mechanism that handles that is the "pull request". There are [many ways to create a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) but the easiest is to just go to [your fork on github](https://github.com/rmcgranaghan/HelioML) and click on the "Pull request" button near the top:  
<img width="1108" alt="Screenshot 2019-05-01 14 02 04" src="https://user-images.githubusercontent.com/947614/57033016-bc42fe00-6c19-11e9-937e-00f18b8b23b7.png">
Then just click the big green "Create pull request" button and input a comment.

**Comment by rmcgranaghan** [comment]
Excellent! Thanks, James. Just created the pull request.

Best,
Ryan

*Ryan McGranaghan* - Aerospace Engineering Scientist | Principal Data
Scientist


          ASTRA, LLC

          282 Century Place, Suite 1000  |  Louisville, CO  80027
          Contact
          WeWork c/o Ryan McGranaghan, 641 S Street NW, Washington, DC 20001
          865.804.2169  |  ryan.mcgranaghan@gmail.com /
rmcgranaghan@astraspace.net |  astraspace.net

**Comment by jmason86** [comment]
Alright, I have now run the entire notebook on our cluster. It's actually significantly slower than it was on Ryan's or my MacBook Pros. After looking up the n1-standard machines that we're using, this isn't a surprise. These machines are in the low 2.x GHz range. 

@mbobra is this acceptable or should we consider switching to higher performance machines (I'm not actually sure what options there are... I didn't see anything as high as the 2.9 GHz on my laptop, which was surprising to me)? 

Another option would be for @rmcgranaghan to see if there's any parallelization that can be done easily in the code. I know that several functions in `scikit-learn` make this super easy with a single kwarg. 

The final option would be to just accept it as it is. It does execute, it just takes a long time. 

Here are the performance numbers: 

Total time for execution: 10 hours 27 minutes
Time to download the 2015 data: 3 minutes
Time for input feature selection: 
* CPU times: user 4h 42min 38s, sys: 10.5 s, total: 4h 42min 48s
* Wall time: 4h 42min 50s

Time for SVM training:
* CPU times: user 19min, sys: 5.37 s, total: 19min 5s
* Wall time: 19min 5s

Time for first confusion matrix
* CPU times: user 1h 50min 7s, sys: 1.31 s, total: 1h 50min 9s
* Wall time: 1h 50min 9s

Time for sensitivity:
* CPU times: user 3h 24min 13s, sys: 34 s, total: 3h 24min 47s
* Wall time: 3h 24min 49s

**Comment by jmason86** [comment]
Alright, sorry for the long delay! We're going to push increasing the processing power of our cloud compute to a future improvement. It's not something that should hold back the merging of this chapter. So it's now been merged!
